<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion4</name>
   <tag></tag>
   <elementGuidId>ac3c7ef7-ee32-4bd9-9a9d-40a70315a069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i158 > div.uHMk6b.fsHoPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i158']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea8cf05e-33af-4ab3-b027-dc0748a6bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uHMk6b fsHoPb</value>
      <webElementGuid>723da6fc-0f18-471b-9fd5-cef9b3b6df1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i158&quot;)/div[@class=&quot;uHMk6b fsHoPb&quot;]</value>
      <webElementGuid>23698f1e-46a4-4cbe-9139-f862bd15d0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i158']/div[2]</value>
      <webElementGuid>abef4bf8-6c2e-45c9-b78e-51d8fe265f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div[4]/label/div/div/div[2]</value>
      <webElementGuid>75782cad-95fc-4468-8ede-49d0b24477ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
