<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion3</name>
   <tag></tag>
   <elementGuidId>82e0701e-c0a2-4013-af7b-04c6eac959be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i155 > div.uHMk6b.fsHoPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i155']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e031109-055b-4de1-a919-156169a7730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uHMk6b fsHoPb</value>
      <webElementGuid>33932c3b-a524-4ef2-8781-85a9172dc973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i155&quot;)/div[@class=&quot;uHMk6b fsHoPb&quot;]</value>
      <webElementGuid>8426ff62-5666-45ab-9f4b-9607c26d91e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i155']/div[2]</value>
      <webElementGuid>c6b874fb-ea93-4b1e-9910-efd8635e2777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div[3]/label/div/div/div[2]</value>
      <webElementGuid>6f1da2bb-0cf4-4cd1-8d2a-e7109f939880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
