<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opcion4</name>
   <tag></tag>
   <elementGuidId>619288b5-1bb6-45f9-89fc-9123c1609210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i14 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i14']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74b4b12f-27ac-47f9-86b5-5ba90c697178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>5d3dd613-a06f-465a-a0ff-c66e9ecf48f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i14&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>8f4efe93-2603-4655-9178-b1a8b9438757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i14']/div[3]/div</value>
      <webElementGuid>bd527dfd-48cf-4190-b2fb-17332d820794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 34 a 41 años.'])[1]/following::div[8]</value>
      <webElementGuid>ac25faa8-c32d-4c54-a83a-d5a9c57481c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 26 a 33 años.'])[1]/following::div[19]</value>
      <webElementGuid>00075039-ca83-4f19-94ce-c9438aefcff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 42 a 49 años.'])[1]/preceding::div[2]</value>
      <webElementGuid>d3e435b9-5052-4428-a808-2d21a2d953d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 50 a 57 años'])[1]/preceding::div[11]</value>
      <webElementGuid>f2330b03-cd6b-4df8-b4ea-1d625c3a2263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/div/div/div/div[3]/div</value>
      <webElementGuid>1e465d7d-5dc4-43fe-a31a-6bddcebe7a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
