<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opcion3</name>
   <tag></tag>
   <elementGuidId>62171f62-8847-4bf7-a15d-25868184ea2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i11 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i11']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1848b6bb-62c4-47b2-a8ff-4ef234554659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>adc742b5-efd2-4ae1-92b1-df7572b077f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i11&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>247f66ed-fe59-41d6-93ba-b33d97cfb4cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i11']/div[3]/div</value>
      <webElementGuid>01b44507-acf9-4893-bf7e-7945930c0e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 26 a 33 años.'])[1]/following::div[8]</value>
      <webElementGuid>53d3385c-d9af-474f-98b0-ca51e7e99b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 18 a 25 años.'])[1]/following::div[19]</value>
      <webElementGuid>c193f505-d5fb-4f26-8445-19d6a2c738ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 34 a 41 años.'])[1]/preceding::div[2]</value>
      <webElementGuid>ec3a4620-1970-43b5-b8f3-9a9799dac1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 42 a 49 años.'])[1]/preceding::div[11]</value>
      <webElementGuid>88b20fde-5023-4a3f-81cc-d029c9009092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/div/div/div[3]/div</value>
      <webElementGuid>4fadfb4a-4a8f-4421-b99c-5e354da91601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
