<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opcion7</name>
   <tag></tag>
   <elementGuidId>65a5641f-cd76-48d2-8b81-70e4f364d9fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i23 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i23']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>469511bd-dfe6-4daf-b74b-020458d5560d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>f4f5dff1-69fb-4da3-92b0-e80442a129ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i23&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>90275659-1d43-4f3d-914d-f34f022a42a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i23']/div[3]/div</value>
      <webElementGuid>d8916764-d8d4-44e6-8a9c-7c758ca347cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 58 a 65 años.'])[1]/following::div[8]</value>
      <webElementGuid>e1923ab4-1555-40af-8fef-af6088950f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 50 a 57 años'])[1]/following::div[19]</value>
      <webElementGuid>150ba293-d143-4177-ae56-74b00adde0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esta pregunta es obligatoria.'])[1]/preceding::div[9]</value>
      <webElementGuid>b4045e9d-2bb4-45f5-93fc-24e11fd36d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[10]</value>
      <webElementGuid>6ff750ea-9cd8-4c25-bbac-f991214347b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label/div/div/div/div[3]/div</value>
      <webElementGuid>14fe4ad1-12b3-4800-b090-5f6fb11bedf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
