<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion3</name>
   <tag></tag>
   <elementGuidId>7a79086a-3857-41ae-a7bf-89ee9d9210b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i79 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i79']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0909303-771f-42ae-a813-93eac54104c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>f08ab655-21ed-4ef7-884e-ff238f0ca998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i79&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>ba55a18e-ad2d-472c-8c61-3901e0b037cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i79']/div[3]/div</value>
      <webElementGuid>cf68666a-3f79-4f89-a85b-b5bb56f2c44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algunos'])[1]/following::div[8]</value>
      <webElementGuid>fef79aa6-4878-482d-9f6c-c1288d103e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí, todos'])[1]/following::div[19]</value>
      <webElementGuid>11f71f26-5db0-4bff-ad31-87da6e2211e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ningunos'])[1]/preceding::div[2]</value>
      <webElementGuid>399ff38e-1dde-476a-bcae-1bff0c05042e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No tengo mascotas'])[1]/preceding::div[11]</value>
      <webElementGuid>657aa246-3523-47d1-8d77-85b24e327390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/span/div/div[3]/label/div/div/div/div[3]/div</value>
      <webElementGuid>930dd574-35d3-40f2-8d78-d4e613eee7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
