<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion1</name>
   <tag></tag>
   <elementGuidId>d5894970-1452-447d-a6b2-e1c503bd36f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i73 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i73']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>994f9522-9537-43f3-88f8-169b68d0ea5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>771c2077-f989-4430-ae09-687223987ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i73&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>469badb0-2dac-4a41-8fe6-d1ea8c0991cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i73']/div[3]/div</value>
      <webElementGuid>bdf92b48-b155-4f48-ba0b-d449b2ea1e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrar la selección'])[1]/following::div[20]</value>
      <webElementGuid>023355f9-feaa-412e-8359-9aa8fe89da29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 7 o mas'])[1]/following::div[25]</value>
      <webElementGuid>963b3bec-0e4d-47e8-abbf-1cca3bc65e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí, todos'])[1]/preceding::div[2]</value>
      <webElementGuid>6b92bb83-6d1f-4244-b861-0152c37e64c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algunos'])[1]/preceding::div[11]</value>
      <webElementGuid>f0e2e410-ad68-419a-ab2b-e5f1006e1115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/span/div/div/label/div/div/div/div[3]/div</value>
      <webElementGuid>17421359-20b0-4d3d-97ae-f485622f5ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
