<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion3</name>
   <tag></tag>
   <elementGuidId>01d214ca-923b-4cff-94a4-8c79cbfcbb3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i63 > div.vd3tt > div.AB7Lab.Id5V1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i63']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc02c01c-a1c3-4cb0-b5b2-fb1d15d55209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>fdcf58dd-41d9-4b33-b6b2-607cd8b407ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i63&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>a0440b28-db04-4107-9942-ad8d4f3b543d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i63']/div[3]/div</value>
      <webElementGuid>ad91fc82-de57-4e54-bd88-a2a3e44254c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 4 a 6'])[1]/following::div[8]</value>
      <webElementGuid>dc470b3d-0596-499b-8b67-c7876c154664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 1 a 3'])[1]/following::div[19]</value>
      <webElementGuid>cc17edf7-fbb3-47ab-bfc8-1322a0e52699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 7 a 10'])[1]/preceding::div[2]</value>
      <webElementGuid>630b75d7-d3fe-4ddd-a4be-ed5956e5c035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De 7 o mas'])[1]/preceding::div[11]</value>
      <webElementGuid>0f972ab0-d460-4453-a585-e5dafcc7d1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/span/div/div[3]/label/div/div/div/div[3]/div</value>
      <webElementGuid>e2564e3a-29b2-4a84-8321-8848aa454b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
