<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opcion5</name>
   <tag></tag>
   <elementGuidId>c1d9d4ce-8cf9-4e5d-ac74-ec8a9eeabd76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i138 > div.uHMk6b.fsHoPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i138']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b99a408-2c77-4ffc-beb8-838fdd3faa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uHMk6b fsHoPb</value>
      <webElementGuid>3ed11e06-c52b-4684-9641-658b9fc29fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i138&quot;)/div[@class=&quot;uHMk6b fsHoPb&quot;]</value>
      <webElementGuid>906539bd-e22a-4f74-9399-3cf08be964ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i138']/div[2]</value>
      <webElementGuid>bde665cf-9a60-4043-94a5-7b4856d30557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/div/div/div[2]</value>
      <webElementGuid>4af3043b-e54d-41ec-bfd4-f59965da123d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
